# This is a basic workflow to help you get started with Actions
name: Build Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Checkout zipper
      uses: actions/checkout@v2
      with:
        repository: avantgarde280/AnyKernel3
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: TwistedKernel
      with:
        arch: arm64
        compiler: proton-clang/master/binutils
        defconfig: twisted_mix2s_defconfig
        image: Image.gz-dtb

    - name: Release build
      uses: appleboy/telegram-action@master
      with:
        to: "543221957" 
        #${{ secrets.CHANNEL_ID }}
        token: "2049951634:AAH9bKEiRZQdnTJ-EJm0U1O8H2WNa7R1KS8"
        #${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: New TwistedKernel is now ready!, took ${{ steps.build.outputs.elapsed_time }} seconds to compiled
        document: ${{ steps.build.outputs.outfile }}, out/.config, out/drivers/media/platform/msm/broadcast/tspp.ko, out/drivers/media/platform/msm/dvb/adapter/mpq-adapter.ko, out/drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko, out/drivers/mmc/card/mmc_test.ko, out/drivers/net/wireless/ath/wil6210/wil6210.ko, out/drivers/platform/msm/msm_11ad/msm_11ad_proxy.ko, out/drivers/soc/qcom/llcc_perfmon.ko, out/net/bridge/br_netfilter.ko
